liongram/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from posts.views import url_view, url_parameter_view, \
      function_view, class_view, index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    # str뒷부분을 view에서 받아서 쓸 수 있다.
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view(), name='cbv'),
    
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('', index, name='index'),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path
from .views import post_create_form_view, post_create_view, post_delete_view, \
    post_detail_view, post_list_view, post_update_view

app_name = 'posts'

urlpatterns = [
    # 네임을 쓰면 ''안에 들어갈 내용이 바뀌어도 html이 post-list를 자동으로 참조함
    path('', post_list_view, name = 'post-list'),
    # path('create/', post_create_view, name = 'post-create'),
    path('create/', post_create_form_view, name = 'post-create'),
    path('<int:id>/', post_detail_view, name = 'post-detail'),
    path('<int:id>/delete', post_delete_view, name = 'post-delete'),
    path('<int:id>/edit', post_update_view, name = 'post-update')
]

liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.

class Post(models.Model):
    image = models.ImageField(verbose_name='이미지',null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일',auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수',default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일',auto_now_add=True)
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

liongram/posts/forms.py
from django import forms
from .models import Post

class PostBaseForm(forms.Form):
    CATEGORY_CHOICES = [
        ('1', '일반'),
        ('2', '계정'),
    ]
    image = forms.ImageField(label = '이미지')
    content = forms.CharField(label = '내용', widget=forms.Textarea)
    category = forms.ChoiceField(label = '카테고리',choices=CATEGORY_CHOICES)

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

liongram/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic.list import ListView
from django.http import Http404, HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostBaseForm, PostCreateForm

def index(request):
    post_list = Post.objects.all().order_by('-created_at') # Post 전체 데이터 조회
    context = {
        'post_list' : post_list,
    }
    return render(request, 'index.html', context)

def post_list_view(request):
    post_list = Post.objects.all() # Post 전체 데이터 조회
    # post_list = Post.objects.filter(writer = request.user) # Post.writer가 현재 로그인인 것 조회
    context = {
        'post_list' : post_list,
    }
    return render(request, 'posts/post_list.html', context)

@login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')    
    else:
        image = request.FILES.get('image')
        content = request.POST.get('content')
        Post.objects.create(
            image = image,
            content = content,
            writer = request.user
        )
        return redirect('index')

def post_create_form_view(request):
    if request.method == 'GET':
        form = PostCreateForm()
        context = {'form' : form}
        return render(request, 'posts/post_form2.html', context)
    else:
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid(): # cleaned_data쓸려면 이거 호출 해야 함
            Post.objects.create(
                image = form.cleaned_data['image'],
                content = form.cleaned_data['content'],
                writer = request.user
            )
        else:
            return redirect('posts:post-create')
        return redirect('index')
    
@login_required
def post_update_view(request, id):
    # post = Post.objects.get(id = id)
     # 500 에러 페이지로 이동을 404페이지로 가도록 해줌
    post = get_object_or_404(Post, id= id, writer = request.user)
    if request.user != post.writer:
        return Http404('잘못된 접근입니다.')
    if request.method == 'GET':
        context = {'post' : post}
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        new_image = request.FILES.get('image')
        content = request.POST.get('content')

        if new_image:
            post.image.delete() # 기존의 이미지 삭제 후 수정된 이미지 추가
            post.image = new_image

        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)

def post_detail_view(request, id):
    try:
        post = Post.objects.get(id = id)

    except Post.DoesNotExist:
        return redirect('index')

    context = {
        'post' : post,
    }
    return render(request, 'posts/post_detail.html', context)

@login_required
def post_delete_view(request, id):
    post = get_object_or_404(Post, id= id, writer = request.user)
    if request.user != post.writer:
        return Http404('잘못된 접근입니다.')
    
    if request.method == 'GET':
        context = { 'post' : post }
        return render(request, 'posts/post_confirm.delete.html', context)
    else:
        post.delete()
        return redirect('index')
    

def url_view(request):
    print('url_view()')
    data = {'code': '1', 'name': 'text'}
    # return HttpResponse('url_view')
    return JsonResponse(data)

def url_parameter_view(request, username):
    print(f'username: {username}')
    print(f'request: {request.GET}')
    return HttpResponse(username)

def function_view(request):
    print(f'request.method: {request.method}')

    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    else:
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')

class class_view(ListView):
    model = Post
    template_name = 'cbv_view.html'

liongram/posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
        {{ object }}
        <br>
    {% endfor %}
</body>
</html>

liongram/posts/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/fbv/">새로고침</a><br>

    <form action = "" method="GET">
        <input type="text" name="var">
        <input type="submit" value="GET 제출">
    </form>

    <form action = "" method="POST"> {% csrf_token %}
        <input type="text" name="var">
        <input type="submit" value="POST 제출">
    </form>
</body>
</html>

liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>{% block title %}{% endblock %} | 라이언 그램</title>
</head>
<body class = 'container'>
    <div>
        {% block content %}
        {% endblock %}
    </div>
    <div>
        <nav>
            <ul class = "bottom-menu-group">
                <li>
                    <a href="{% url 'index' %}">
                        <img src="{% static 'icons/home_outlined_black_36dp.svg' %}" alt="홈">
                    </a>
                </li>
                <li>
                    <img src="{% static 'icons/search_outlined_black_36dp.svg' %}" alt="검색">
                </li>
                <li>
                    <a href="{% url 'posts:post-create' %}">
                        <img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}" alt="추가">    
                    </a>
                </li>
                <li>
                    <img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요">
                </li>
                <li>
                    <img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}" alt="계정">
                </li>
            </ul>
        </nav>
    </div>
</body>
</html>

liongram/templates/index.html
{% extends 'base.html' %}
{% load static %}

% block title % index % endblock %

{% block content %}
<main>
    <div class = "card-list">
        {% for post in post_list %}
            {% include 'mixin/posts/post_card.html' with detail=False %}
        {% endfor %}
    </div>
</main>
{% endblock %}

liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class = "card">
    <div class = "card_header">
        <img src="http://via.placeholder.com/32x32" alt="프로필이미지">
        <a href="">
            <span class = "card_user-name">{{ post.writer }}</span>
        </a>
        {% if request.user == post.writer %}
            <a href="{% url 'posts:post-update' post.id %}">수정하기</a> 
            <a href="{% url 'posts:post-delete' post.id %}">삭제하기</a>
        {% endif %}
    </div>
    <div class = "card_body">
        <div>
            {% if post.image %}
                <img class = "card_image" src="{{ post.image.url }}" alt="card_img">
            {% else %}
                <img class = "card_image" src="http://via.placeholder.com/600x600" alt="card_img">
            {% endif %}
        </div>
        <div class = 'card_btn-group'>
            <div>
                <img class = 'card_btn' src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요">
                <img class = 'card_btn' src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글">
                <img class = 'card_btn' src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유">
            </div>
            <div>
                <img class = 'card_btn' src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="즐겨찾기">   
            </div>
        </div>
        <div class = "card_content">
            <span class = "card_like-num">좋아요 00개</span>
            <div class = "card_main-text">
                <p>
                    <span class="card_user-name">{{ post.writer }}</span>
                    {% if not detail %}
                        {{post.content|truncatechars:35}} <!-- 디테일이 아니면 35자만 보여줌 -->
                    {% else %}
                        {{ post.content }} <!-- 더보기 눌러서 디테일 화면 들어가면 모든 텍스트 다 보여줌 -->
                    {% endif %}
                </p>
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">더보기</a> 
                {% endif %}
                <!-- /posts/{{ post.id }} -->
            </div>
            <div>
                <p>댓글 {{ post.comment_set.all.count }}개 
                    {% if not detail %}
                        <a href="{% url 'posts:post-detail' post.id %}">모두 보기</a>
                    {% endif %}
                </p>
                <ul class = "card_comment-group">
                    {% if not detail %}
                        {% for comment in post.comment_set.all|slice:":1"  %} 
                            <li>
                                <p><span class = "card_user-name">{{comment.writer}}</span>{{ comment.content }}</p>
                            </li>
                        {% endfor %}
                    {% else %}
                        {% for comment in post.comment_set.all %}  
                            <li>
                                <p><span class = "card_user-name">{{comment.writer}}</span>{{ comment.content }}</p>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
                <p class = "card_created_date">{{ post.created_at|date:"Y년 m월 d일" }}</p>
            </div>
        </div>
    </div>
</div>

liongram/templates/posts/post_confirm.delete.html
{% extends 'base.html' %}
{% block title %}글 삭제{% endblock %}

{% block content %}
<h1>Post 삭제 화면</h1>
<form action = "" method = "POST">
    {% csrf_token %}
    <p>한번 삭제된 데이터는 복구가 불가능 합니다.</p>
    <p>그래도 삭제 하시겠습니까? ID : {{ post.id }}</p>

    <a href="{% url 'index' %}">돌아가기</a>
    <input type = "submit" value = "삭제하기"> 
</form>
<hr>  
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}

liongram/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}글 상세{% endblock %}

{% block content %}
<h1>Post 상세 화면</h1>
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}

liongram/templates/posts/post_form.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 글 입력 {% endblock %}

{% block content %}
<h1>입력화면</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for ="id_image">이미지</label>
        {% if post.image %}
            <p>현재: <a href="{{ post.image.url }}">{{ post.image.name }}</a></p>
            <p>변경: <input type="file" name="image" accept="image/" id="id_image"></p>
        {% else %}
            <input type="file" name="image" accept="image/" id="id_image">
        {% endif %}
    </div>
    <div>
        <label for="id_content">내용</label>
        <textarea name="content" id="id_content" clos="30" rows="10">
            {% if post %}
                {{ post.content }}
            {% endif %}
        </textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

liongram/templates/posts/post_form2.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 글 입력 {% endblock %}

{% block content %}
<h1>입력화면</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ form.as_p }}
    </div>
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

liongram/templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %}Post 목록 화면{% endblock %}

{% block content %}
<h1>Post 목록 화면</h1>
<!-- {{ post_list }} -->

{% for post in post_list %}
    <div>
        {{ post.id }}<br>
        {{ post.image }}<br>
        {{ post.content }}<br>
        {{ post.created_at }}<br>
        {{ post.writer }}<br>
    </div>
{% endfor %}
{% endblock %}

liongram/templates/posts/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Post 업데이트 화면</h1>
</body>
</html>